"""Add patient table

Revision ID: 40d3f3b14e9f
Revises: 
Create Date: 2025-06-05 23:46:42.883347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40d3f3b14e9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_logs')
    op.drop_table('patient_info')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_of_assessment', sa.Date(), nullable=False))
        batch_op.alter_column('full_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('clinician_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('assessment_date')
        batch_op.drop_column('contact')

    with op.batch_alter_table('prediction_log', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('patient_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('assessment_date', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('clinician_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('date_of_assessment')
        batch_op.drop_column('contact_info')

    op.create_table('patient_info',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('contact_info', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('date_of_assessment', sa.DATE(), nullable=True),
    sa.Column('clinician_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prediction_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('A1c_Percent', mysql.FLOAT(), nullable=True),
    sa.Column('eGFR', mysql.FLOAT(), nullable=True),
    sa.Column('Urine_Microalbumin_mg_L', mysql.FLOAT(), nullable=True),
    sa.Column('Serum_Creatinine_umol_L', mysql.FLOAT(), nullable=True),
    sa.Column('BMI_kg_m2', mysql.FLOAT(), nullable=True),
    sa.Column('Age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Ave_SBP_mmHg', mysql.FLOAT(), nullable=True),
    sa.Column('Ave_DBP_mmHg', mysql.FLOAT(), nullable=True),
    sa.Column('Urine_Creatinine_umol_L', mysql.FLOAT(), nullable=True),
    sa.Column('Diabetes_Status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Risk_Score', mysql.FLOAT(), nullable=True),
    sa.Column('Risk_Category', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Prediction_Time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
